### PR TITLE
fixes #6

### LINKED ISSUE #6: Using the same port as openmediavault-webgui breaks nginx configuration
OpenMediaVault `mkconf/nginx.d/webgui` adds an IPv6 prefix to the listening port.
So if you create a server wich should listen on the same port as the webgui server, nginx fails to start because port 80 and/or 443 are already in use.

This could be resolved by adding the IPv6 prefix to `mkconf/nginx.d/90-nginx-server`

	:/usr/share/openmediavault/mkconf/nginx.d $ diff -u 90-nginx-server~ 90-nginx-server
	--- 90-nginx-server~    2014-11-04 15:31:02.000000000 +0100
	+++ 90-nginx-server     2014-11-30 08:12:27.483801276 +0100
	@@ -127,7 +127,7 @@
				 default_server=" default_server"
			 fi

	-        echo "    listen ${port}${default_server};" >> ${config}
	+        echo "    listen [::]:${port}${default_server};" >> ${config}
		 fi

		 # SSL config
	@@ -138,7 +138,7 @@
				 ssl_default_server=" default_server"
			 fi

	-        echo "    listen ${ssl_port}${ssl_default_server} ssl;" >> ${config}
	+        echo "    listen [::]:${ssl_port}${ssl_default_server} ssl;" >> ${config}
			 echo "    ssl_certificate     ${OMV_CERTIFICATE_DIR}/certs/${OMV_CERTIFICATE_PREFIX}${sslcertificateref}.crt;" >> ${config}
			 echo "    ssl_certificate_key ${OMV_CERTIFICATE_DIR}/private/${OMV_CERTIFICATE_PREFIX}${sslcertificateref}.key;" >> ${config}
		 fi

### PR DESCRIPTION
**Pull request by DipSwitch**
As of commit [r1064] http://sourceforge.net/p/openmediavault/code/1064/ openmediavault uses IPv6 by default.
To avoid openmediavault-nginx to break the nginx configuration when using port 80 or 443 the servers created by the plugin must also include the IPv6 prefix in the listen directive.

### CODE REVIEW

**Comment by nohatssir** [comment]
I forgot about this one over the holidays. I've already had the [::] in once but there's a problem with it. When using newer versions of Nginx (as with the dotdeb repo) you need to set ipv6only=off for it to work with both IPv4 and IPv6. The problem is that you can only set ipv6only=off once on one port. Just adding it in the mkconf won't do since the config test fails.

**Comment by nohatssir** [comment]
Ugh, the validation complexity just grows more horrible for each day :( That's the reason why I haven't allowed setting the same port as the web interface for OMV, there's so many things to check for and adds a lot of complexity to both validation and the mkconf file.

**Comment by DipSwitch** [comment]
No problem :)

Oke, didn't know nginx changed it's configuration again. I'll keep my changes and see when it breaks and how to maybe fix them when the time is there.

**Comment by nohatssir** [comment]
I think I'll reopen this just so that I don't forget about it :) If I can come up with a simple way of improving your solution I'll try to implement it. Thanks anyway! Don't hesitate to think of one yourself!

**Comment by nohatssir** [comment]
Closing this in favoor of #12 (which is still not complete though).

**Pull request closed without merging**
